name: 'Radiant Map'
description: 'Run Radiant Map'
inputs:
  RDF:
    description: 'path to rdf file'
    required: true

runs:
  using: "composite"
  steps:
    - run: pnmainc ${{ github.action_path }}/par.tcl ${{ inputs.RDF }}
      shell: bash
